sudo: false
language: ruby
rvm:
  - '2.3.0'
  - '2.2'
  - '2.1'
env:
  - GEM=will_paginate
  - GEM=kaminari
gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_head.gemfile
matrix:
  allow_failures:
  - gemfile: gemfiles/rails_head.gemfile
