sudo: false
language: ruby
rvm:
  - '2.3.0'
  - '2.2'
  - '2.1'
env:
  - GEM=will_paginate
  - GEM=kaminari
gemfile:
  - gemfiles/Gemfile.rails-3-2
  - gemfiles/Gemfile.rails-4-0
  - gemfiles/Gemfile.rails-4-1
  - gemfiles/Gemfile.rails-4-2
  - gemfiles/Gemfile.rails-head
matrix:
  allow_failures:
  - gemfile: gemfiles/Gemfile.rails-head
